include: package:lints/core.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    non_constant_identifier_names: ignore

linter:
  # For more https://dart-lang.github.io/linter/lints/index.html.
  rules:
    - avoid_print
    - avoid_empty_else
    - avoid_web_libraries_in_flutter
    - empty_statements
    - prefer_relative_imports

    - always_declare_return_types
    - avoid_bool_literals_in_conditional_expressions
    - avoid_function_literals_in_foreach_calls
    - avoid_unnecessary_containers
    - camel_case_extensions
    - camel_case_types
    - empty_catches
    - no_leading_underscores_for_library_prefixes
    - no_leading_underscores_for_local_identifiers
    - file_names
    - library_prefixes
    - missing_whitespace_between_adjacent_strings
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_null_aware_operators
    - prefer_null_aware_method_calls
    - prefer_spread_collections
    - recursive_getters
    - sized_box_for_whitespace
    - type_annotate_public_apis
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_string_interpolations
    - use_colored_box
    - use_decorated_box
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_rethrow_when_possible
    - use_raw_strings
    - use_setters_to_change_properties
    - secure_pubspec_urls