name: stook_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  sqlite3: ^2.4.0
  path_provider: ^2.1.2
  path: ^1.9.0
  octopus: ^0.0.8
  provider: ^6.1.2
  collection: ^1.18.0
  injector: ^3.0.0
  stook_database:
    path: 'packages/stook_database'
  stook_importance_algorithm:
    path: 'packages/importance_algorithm'
  stook_shared:
    path: 'packages/stook_shared'
  flutter_markdown_editor:
    path: 'packages/flutter_markdown_editor'
  drift_db_viewer: ^2.1.0
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.5
  flutter_bloc: ^8.1.5
  shared_preferences: ^2.2.2
  freezed_annotation: ^2.4.1
  loader_overlay: ^4.0.0
  intl: ^0.18.1
  flutter_localization: ^0.2.0
  adaptive_theme: ^3.6.0
  flutter_markdown: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  freezed: ^2.5.2
  drift_dev: ^2.16.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
