@startuml "entity"

hide empty members

entity "Студент" as user {
    Идентификатор
    Имя
    Адрес электронной почты
    Дата регистрации
}

entity "Расписание" as schedule {
    Идентификатор
    Название
    Признак активности
}

entity "Занятие" as lesson {
    Идентификатор
    Название
    Номер
    Номер недели
}

enum "День недели" as day {
    Понедельник
    Вторник
    Среда
    Четверг
    Пятница
    Суббота
}

enum "Тип занятия" as lessonType {
    Лекция
    Практика
    Лабораторная
}

entity "Заметка" as note {
    Идентификатор
    Название
    Текст
    Дата создания
    Дата изменения
    Признак избранности
}

entity "Ресурс" as resource {
    Идентификатор
    Название
    Ссылка
    Дата добавления
    Признак избранности
}

enum "Тип ресурса" as resourceType {
    Книга
    Статья
    Видео
    Сайт
}

entity "Задача" as task {
    Идентификатор
    Название
    Текст
    Дата создания
    Дата крайнего срока
    Признак выполнения
    Список подзадач
    Список зависимых задач
}

enum "Приоритет" as priority {
    A
    B
    C
}

user "1" -- "*" schedule : "имеет"

schedule "1" -- "*" lesson : "содержит"
lesson "1" -l- "1" lessonType : "имеет"
lesson "*" -r- "1" day : "имеет"

'user "1" -- "*" note : "имеет"
lesson "1" -- "*" note : "имеет"

'user "1" -- "*" resource : "имеет"
lesson "1" -- "*" resource : "имеет"

resource "1" -- "*" resourceType : "имеет"

user "1" -- "*" task : "имеет"
task "*" -- "1" priority : "имеет"

@enduml