@startuml "entity"

'add styles for er-diagram
hide empty members
' hide circle
' skinparam linetype ortho
' !theme plain


entity "Расписание" as schedule {
    Идентификатор
    Название
    Номер активной недели
}

entity "Занятие" as lesson {
    Идентификатор
    Название
    Преподаватель
    Место проведения
    Тип занятия
    Время начала
    Время окончания
    Номер недели
    День недели
}

enum "День недели" as day {
    Понедельник
    Вторник
    Среда
    Четверг
    Пятница
    Суббота
}

enum "Тип занятия" as lessonType {
    Лекция
    Практика
    Лабораторная
}

entity "Заметка" as note {
    Идентификатор
    Название
    Текст
    Дата создания
    Дата изменения
    Признак избранности
}

entity "Ресурс" as resource {
    Идентификатор
    Название
    Ссылка
    Дата добавления
    Тип ресурса
    Признак избранности
}

enum "Тип ресурса" as resourceType {
    Книга
    Статья
    Видео
    Сайт
}

entity "Задача" as task {
    Идентификатор
    Название
    Текст
    Приоритет
    Статус
    Дата создания
    Дата крайнего срока
    Список подзадач
    Список зависимых задач
}

enum "Приоритет" as priority {
    A
    B
    C
}

enum "Статус" as status {
    Новая
    В процессе
    Завершена
    Просрочена
}

schedule "1" -- "*" task : "содержит"
schedule "1" -- "*" lesson : "содержит"
lesson "1" -l- "1" lessonType : "имеет"
lesson "*" -r- "1" day : "имеет"

'user "1" -- "*" note : "имеет"
lesson "1" -- "*" note : "имеет"

'user "1" -- "*" resource : "имеет"
lesson "1" -- "*" resource : "имеет"

resource "1" -- "*" resourceType : "имеет"

task "*" -- "1" priority : "имеет"
task "*" -- "1" status : "имеет"

@enduml