@startuml TaskPrioritySchema

'left to right direction

hide circle
hide empty members

class "Проектирование Базы Данных" as DB {
    Приоритет: A (9)
    Приоритет зависимости: 36
}

class "Создать связи" as Relations {
    Приоритет: C (3)
    Приоритет зависимости: 45
}

class "Создать сущности" as Entities {
    Приоритет: B (6)
    Приоритет зависимости: 93
}

class "Создать таблицы" as Tables {
    Приоритет: B (6)
    Приоритет зависимости: 45
}

class "Проектирование архитектуры" as Architecture {
    Приоритет: A (9)
    Приоритет зависимости: 27
}

class "Выбрать стек технологий" as TechStack {
    Приоритет: B (6)
    Приоритет зависимости: 78
}

class "Выбрать используемые фреймворки" as Frameworks {
    Приоритет: B (6)
    Приоритет зависимости: 36
}

class "Разработка приложения" as Development {
    Приоритет: A (9)
    Приоритет зависимости: 18
}

class "Оформление отчетности" as Reporting {
    Приоритет: C (3)
    Приоритет зависимости: 6
}

class "Оформление презентации" as Presentation {
    Приоритет: C (3)
    Приоритет зависимости: 6
}

class "Защита проекта" as Protection {
    Приоритет: B (6)
    Приоритет зависимости: 0
}

DB --> Entities : Подзадача
DB --> Tables : Подзадача
DB --> Relations : Подзадача

Relations -u-> Entities : Зависит от

Architecture --> TechStack : Подзадача
Architecture --> Frameworks : Подзадача

Frameworks --> TechStack : Зависит от

Architecture --> DB : Зависит от

Development --> Architecture : Зависит от

Protection --> Reporting : Зависит от
Protection --> Presentation : Зависит от

Reporting --> Development : Зависит от
Presentation --> Development : Зависит от



@enduml